// 4. You are given two strings s and t.
// ‌
// String t is generated by random shuffling string s and then add one more letter at a random position.
// ‌
// Return the letter that was added to t.
// ‌
// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// ‌
// Example 2:
// Input: s = "", t = "y"
// Output: "y"
// ‌
// Constraints:
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.
// ‌

import java.util.Scanner;

public class Question_4 {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String s = scanner.nextLine();
        String t = scanner.nextLine();

        char added_char = getAddedChar(s, t);
        System.out.println(added_char);
        scanner.close();
    }

    static char getAddedChar(String s, String t) {
        int[] freq = new int[26];
        for(char ch : s.toCharArray())
            freq[ch - 'a']++;
        for(char ch : t.toCharArray())
            freq[ch - 'a']--;
        
        for(int i = 0; i < 26; i++) {
            if(freq[i] == 1) return (char)('a' + i);
        }
        return ' ';
    }
}
